1 修复通用mapper的jpa-api依赖传递问题 默认同时使用hibernate和mapper 所以需要排除mapper的jpa-api依赖 详情参见具体处的注释  ，此问题可能会导致启动时报Caused by: java.lang.NoSuchMethodError: javax.persistence.Table.indexes()[Ljavax/persistence/Index; 错误 更新到此版本即可。